import { FiDownload, FiExternalLink } from "react-icons/fi";

interface ImageResultProps {
  imageUrl: string;
}

export default function ImageResult({ imageUrl }: ImageResultProps) {
  const handleDownload = () => {
    window.open(imageUrl, "_blank");
  };

  return (
    <div
      style={{
        marginTop: "16px",
        borderRadius: "16px",
        overflow: "hidden",
        border: "1px solid var(--border-color)",
        background: "var(--bg-card)",
        position: "relative",
      }}
      className="animate-fade-in"
    >
      <div
        style={{
          position: "relative",
          width: "100%",
          paddingTop: "100%", // 1:1 Aspect Ratio
        }}
      >
        <img
          src={imageUrl}
          alt="Generated AI result"
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%",
            objectFit: "cover",
          }}
        />
      </div>
      
      <div
        style={{
          padding: "12px 16px",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          background: "rgba(26, 31, 53, 0.8)",
          backdropFilter: "blur(10px)",
          borderTop: "1px solid var(--border-color)",
        }}
      >
        <span style={{ fontSize: "12px", color: "var(--text-secondary)", fontWeight: 500 }}>
          Generated by X-LLM Image Engine
        </span>
        <div style={{ display: "flex", gap: "10px" }}>
          <button
            onClick={handleDownload}
            style={{
              background: "none",
              border: "none",
              color: "var(--text-secondary)",
              cursor: "pointer",
              padding: "4px",
              display: "flex",
              alignItems: "center",
              gap: "6px",
              fontSize: "12px",
              transition: "color 0.2s",
            }}
            onMouseOver={(e) => (e.currentTarget.style.color = "var(--accent-indigo)")}
            onMouseOut={(e) => (e.currentTarget.style.color = "var(--text-secondary)")}
          >
            <FiDownload size={14} /> Download
          </button>
          <a
            href={imageUrl}
            target="_blank"
            rel="noreferrer"
            style={{
              background: "none",
              border: "none",
              color: "var(--text-secondary)",
              cursor: "pointer",
              padding: "4px",
              display: "flex",
              alignItems: "center",
              gap: "6px",
              fontSize: "12px",
              textDecoration: "none",
              transition: "color 0.2s",
            }}
            onMouseOver={(e) => (e.currentTarget.style.color = "var(--accent-indigo)")}
            onMouseOut={(e) => (e.currentTarget.style.color = "var(--text-secondary)")}
          >
            <FiExternalLink size={14} /> Open
          </a>
        </div>
      </div>
    </div>
  );
}
